### ISSUE TITLE
mayavi error in installation 

### ISSUE THREAD

**Issue by madinwei** [ivalab/KGN#2]
Hello Ivalab , 
Thank you for your awesome work in KGN.

I am trying to implement KGN, and I am following your [INSTALL.md ](https://github.com/ivalab/KGN/blob/main/docs/INSTALL.md), you have specified that you used Python 3.8. I am using the same, however, I have this issue with mayavi installation since it's not supported in Python 3.8:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing Python installation in your environment:

Specifications:

```
  - mayavi -> python[version='2.7.*|3.4.*|3.5.*|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0']

Your python: python=3.8

If Python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - mayavi -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35
```
and you didn't specify in the [INSTALL.md ](https://github.com/ivalab/KGN/blob/main/docs/INSTALL.md) how to install mayavi. 
I will appreciate any help or guidance since I want to use Python 3.8.

**Comment by yiyeChen** [comment]
Hi @madinwei,

Thanks for your interest in our work! I am able to install mayavi simply with pip following the [doc](https://docs.enthought.com/mayavi/mayavi/installation.html#installing-with-pip). However as specified in the doc, you need to install the dependencies first. Can you try with the following commands?

```bash
pip install vtk
pip install PyQt5
pip install mayavi
```

**Comment by madinwei** [comment]
@yiyeChen 
thank you for your replay, I used pip to install vtk , PyQt5, and mayavi. but I received that error. So I change my Python to 3.7. and now it is working after I use pip `install -U PyQt5 `
and the demo script is working.

**Comment by ymxlzgy** [comment]
I don't know why. But in my case, these pip commands were not working for mayavi installation. I instead solved this problem by installing pyface, pyqt, mayavi, traits, traitsui, etc by conda, following instructions in Contact-Graspnet [here](https://github.com/NVlabs/contact_graspnet/blob/main/contact_graspnet_env.yml)
